# Generated by Django 4.0 on 2024-01-02 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location_id', models.BigIntegerField(db_index=True, unique=True)),
                ('applicant', models.CharField(help_text='name of the truck/restaurant', max_length=255)),
                ('facility_type', models.CharField(choices=[('P', 'Push Cart'), ('T', 'Truck')], db_index=True, help_text="if it's truck, push cart etc.", max_length=30, null=True)),
                ('cnn', models.BigIntegerField()),
                ('location_description', models.TextField(null=True)),
                ('address', models.TextField()),
                ('block_lot', models.CharField(max_length=10, null=True)),
                ('block', models.CharField(max_length=10, null=True)),
                ('lot', models.CharField(max_length=10, null=True)),
                ('permit', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('EXP', 'Expired'), ('APV', 'Approved'), ('REQ', 'Requested'), ('ISD', 'Issued'), ('SPD', 'Suspend')], db_index=True, max_length=20)),
                ('food_items', models.TextField(null=True)),
                ('x', models.CharField(max_length=20, null=True)),
                ('y', models.CharField(max_length=20, null=True)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=20, max_digits=40)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=40)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('schedule', models.URLField()),
                ('days_hours', models.CharField(max_length=60, null=True)),
                ('noi_sent', models.CharField(max_length=10, null=True)),
                ('approved', models.DateTimeField(null=True)),
                ('received', models.BigIntegerField()),
                ('prior_permit', models.BooleanField(db_index=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('fire_prevention_district', models.CharField(max_length=5, null=True)),
                ('police_district', models.CharField(max_length=10, null=True)),
                ('supervisor_district', models.CharField(max_length=10, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('neighbourhoods', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
