# Generated by Django 4.0 on 2024-01-03 09:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326),
        ),
    ]
